### ISSUE TITLE
Fail to run cell_signaling on Seurat data

### ISSUE THREAD

**Issue by tinjac** [SCA-IRCM/SingleCellSignalR#1]
Hi!

First of all, thanks for an exciting preprint! 

Excited about the new package, I've tried your package on my Seurat dataset using the code suggested in the supplementary material.

However, when running cell_signaling function, I get the following error:
> No such file as table_dge_cluster 1.txt in the cluster-analysis folder
> No such file as table_dge_cluster 2.txt in the cluster-analysis folder
> No such file as table_dge_cluster 3.txt in the cluster-analysis folder
> No such file as table_dge_cluster 4.txt in the cluster-analysis folder
> No such file as table_dge_cluster 5.txt in the cluster-analysis folder
> No such file as table_dge_cluster 6.txt in the cluster-analysis folder
> No such file as table_dge_cluster 7.txt in the cluster-analysis folder
> No such file as table_dge_cluster 8.txt in the cluster-analysis folder
> No such file as table_dge_cluster 9.txt in the cluster-analysis folder
> No such file as table_dge_cluster 10.txt in the cluster-analysis folder
> Paracrine signaling: 
> Checking for signaling between cell types

In the documentation/preprint I could not find any requirement that I have to save those tables first... Any explanation? Or if I need to save the differentially expressed genes first, could you please specify the format that table_dge_cluster 10.txt should have?

Thank you very much for your help!

Code I ran: 
```
library(Seurat)
library(SingleCellSignalR)
cluster = as.numeric(Idents(MySeuratObject))
data=data.frame(MySeuratObject[['RNA']]@data)
signal=cell_signaling(data=data,genes=row.names(MySeuratObject),cluster=cluster)
```

[Run with R 3.6.1, Seurat 3.0.2, SingleCellSignalR 0.0.1.2]

**Comment by SCA-IRCM** [comment]
Hi!
First of all thanks a lot for using our package.

The message you get :

> No such file as table_dge_cluster X.txt in the cluster-analysis folder

is normal because the function doesn't find the files in the cluster-analysis folder since you haven't run the "cluster_analysis()" function before. However this step is not strictly required since it is only used for annotation of the interactions (under the _interaction type_ column; as "specific" if the ligand and the receptor are differentially expressed in their respective clusters or simply "paracrine" if not).  It doesn't change the interactions nor their associated LRscores in the functions output. 

I hope this helps!

Yours,

Simon

**Comment by duernaT** [comment]
Hi, thank you for this wonderful package.

I just found I can not install this package by typing:  "devtools::install_github(repo = "https://github.com/SCA-IRCM/SingleCellSignalR_v1", subdir = "SingleCellSignalR") ".

And my R is 4.0.0,
here is the error message I received: 

" Failed to install 'SingleCellSignalR' from GitHub:
    unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/4.0:
   URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/4.0/PACKAGES'  can not open. 

I am relatively new to R, can you please help me out? 

Thank you!

**Comment by duernaT** [comment]
Thank you for this wonderful package!~
i
