### ISSUE TITLE
Plese provide example_data.txt file

### ISSUE THREAD

**Issue by stemangiola** [SCA-IRCM/SingleCellSignalR#2]
Thanks for the package.

I would like to run the vignette commands with a positive control file. Could you please provide somewhere the 

example_data.txt

file, that is called here
```
file <- "example_data.txt"
```

**Comment by SCA-IRCM** [comment]
Hello,
Thanks for using it! 
You can find the file (and others) in the Demo repository (https://github.com/SCA-IRCM/Demo).

Yours,

SCA

**Comment by stemangiola** [comment]
Thanks.
