### ISSUE TITLE
Use own marker genes instead of those generated by cluster_analysis

### ISSUE THREAD

**Issue by Mushin** [SCA-IRCM/SingleCellSignalR#20]
I'd like to specify my own marker gene info for **cell_signaling** (as the function is quite slow), but there doesn't seem to be an argument for this. 

So is it possible to put my own marker genes files in the correct location, so they are used instead of generating "No such file as table_dge_Fib.txt in the cluster-analysis folder"? 

_If so, please can you explain where the files containing DE genes (markers) from **cluster_analysis** are saved / read from?_

Edit: I found the location of the files in the "cluster-analysis" folder. But it would be useful to specify the DE genes files in an argument also.

**Comment by SCA-IRCM** [comment]
Hi,
I agree, it would be useful since the **cluster_analysis()** function is quite slow (it depends on edgeR that can take a non-negligible amount of time for big datasets).
It may be in the next release!

Thanks for using **SingleCellSignalR**!

SCA
