### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value)

### ISSUE THREAD

**Issue by hemadelon** [SCA-IRCM/SingleCellSignalR#4]
Thank you for this awesome package!

I'm performing analysis on a Seurat object, as you've described in the supplementary information.
This is the code I'm using:

```
library(SingleCellSignalR)
cluster = as.numeric(Idents(myObject))
data = data.frame(myObject[['RNA']]@data)
signal = cell_signaling(data=data, genes=row.names(myObject), cluster=cluster)
```

I get the error:
`Error in .rowNamesDF<-(x, value = value) : invalid 'row.names' length`

I'm not sure of the reason for this error.
Hoping someone can help me out!

**Comment by SCA-IRCM** [comment]
Hi,
The code you typed should work. Make sure `length(row.names(myObject))==nrow(data)` and `length(cluster)==ncol(data)`. You can also check that` typeof(genes)=="character"`.
If every test above give `TRUE` send me a message on this issue.

Thanks for using **SingleCellSignalR**!

SCA

**Comment by hemadelon** [comment]
It's actually working now! Thank you!
